In [1]:
import torch
import numpy as np
import os

In [5]:
a = torch.arange(start=10, end=20, step=4)
b = torch.arange(start=5, end=15, step=4)

In [6]:
a.shape, b.shape

(torch.Size([3]), torch.Size([3]))

In [7]:
print(a)
print(b)

tensor([10, 14, 18])
tensor([ 5,  9, 13])


In [8]:
a + b

tensor([15, 23, 31])

In [9]:
a - b

tensor([5, 5, 5])

In [10]:
a * b # Element wise multiplication

tensor([ 50, 126, 234])

In [11]:
a / b

tensor([2.0000, 1.5556, 1.3846])

In [12]:
a % b

tensor([0, 5, 5])

In [14]:
torch.dot(a,b)

tensor(410)

In [15]:
c = torch.ones(3)
c

tensor([1., 1., 1.])

In [16]:
c = c + a
c

tensor([11., 15., 19.])

In [17]:
c.add_(a) # Equivalent to c = c + a

tensor([21., 29., 37.])

In [18]:
c

tensor([21., 29., 37.])

In [19]:
a.pow(2)

tensor([100, 196, 324])

In [20]:
a**2

tensor([100, 196, 324])

In [24]:
a > 10

tensor([False,  True,  True])

In [25]:
# Matrix multiplication

A = torch.rand(size=(3,3))
B = torch.rand(size=(3,3))

A @ B

tensor([[1.5366, 0.4852, 1.2035],
        [0.7956, 0.3462, 0.4392],
        [0.7175, 0.2278, 0.5870]])

In [26]:
A.matmul(B)

tensor([[1.5366, 0.4852, 1.2035],
        [0.7956, 0.3462, 0.4392],
        [0.7175, 0.2278, 0.5870]])

In [28]:
C = torch.rand(size=(3,3))
C

tensor([[0.7198, 0.4900, 0.5202],
        [0.6397, 0.3984, 0.1847],
        [0.2177, 0.6754, 0.5607]])

In [30]:
C.matrix_exp()

tensor([[2.5509, 1.2748, 1.1708],
        [1.2786, 1.9377, 0.6381],
        [0.8533, 1.3101, 2.0443]])

In [31]:
C.matrix_power(3)

tensor([[1.4202, 1.3323, 1.0818],
        [1.0368, 0.9525, 0.7892],
        [1.1146, 1.0220, 0.8189]])

In [32]:
# Broadcasting

A

tensor([[0.7743, 0.8858, 0.5574],
        [0.9427, 0.0456, 0.2731],
        [0.3090, 0.4990, 0.2252]])

In [33]:
A + 1

tensor([[1.7743, 1.8858, 1.5574],
        [1.9427, 1.0456, 1.2731],
        [1.3090, 1.4990, 1.2252]])

In [34]:
A - 1

tensor([[-0.2257, -0.1142, -0.4426],
        [-0.0573, -0.9544, -0.7269],
        [-0.6910, -0.5010, -0.7748]])

In [35]:
A * 5

tensor([[3.8714, 4.4291, 2.7870],
        [4.7137, 0.2282, 1.3653],
        [1.5448, 2.4950, 1.1259]])

In [36]:
A.shape

torch.Size([3, 3])

In [37]:
D = torch.ones(1,3)
D

tensor([[1., 1., 1.]])

In [38]:
A - D

tensor([[-0.2257, -0.1142, -0.4426],
        [-0.0573, -0.9544, -0.7269],
        [-0.6910, -0.5010, -0.7748]])

In [39]:
A + D

tensor([[1.7743, 1.8858, 1.5574],
        [1.9427, 1.0456, 1.2731],
        [1.3090, 1.4990, 1.2252]])

In [40]:
A * D

tensor([[0.7743, 0.8858, 0.5574],
        [0.9427, 0.0456, 0.2731],
        [0.3090, 0.4990, 0.2252]])

In [41]:
A / D

tensor([[0.7743, 0.8858, 0.5574],
        [0.9427, 0.0456, 0.2731],
        [0.3090, 0.4990, 0.2252]])

In [42]:
E = torch.ones((3,1))
E

tensor([[1.],
        [1.],
        [1.]])

In [43]:
A + E

tensor([[1.7743, 1.8858, 1.5574],
        [1.9427, 1.0456, 1.2731],
        [1.3090, 1.4990, 1.2252]])

In [44]:
torch.sum(E)

tensor(3.)

In [45]:
torch.sum(A)

tensor(4.5121)

In [46]:
torch.max(D)

tensor(1.)

In [47]:
torch.min(D)

tensor(1.)

In [48]:
torch.max(D, dim=1) #row

torch.return_types.max(values=tensor([1.]), indices=tensor([0]))

In [49]:
torch.max(D, dim=0) # col

torch.return_types.max(values=tensor([1., 1., 1.]), indices=tensor([0, 0, 0]))

In [50]:
torch.abs(-C)

tensor([[0.7198, 0.4900, 0.5202],
        [0.6397, 0.3984, 0.1847],
        [0.2177, 0.6754, 0.5607]])

In [52]:
torch.argmax(B)

tensor(6)

In [54]:
torch.mean(A, dim=1)

tensor([0.7392, 0.4205, 0.3444])

In [55]:
torch.mean(A, dim=0)

tensor([0.6753, 0.4768, 0.3519])

In [56]:
torch.mean(A)

tensor(0.5013)

In [57]:
torch.eq(C,B)

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [58]:
torch.eq(C, C)

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [65]:
torch.sort(A, descending=True)

torch.return_types.sort(values=tensor([[0.8858, 0.7743, 0.5574],
        [0.9427, 0.2731, 0.0456],
        [0.4990, 0.3090, 0.2252]]), indices=tensor([[1, 0, 2],
        [0, 2, 1],
        [1, 0, 2]]))

In [63]:
A

tensor([[0.7743, 0.8858, 0.5574],
        [0.9427, 0.0456, 0.2731],
        [0.3090, 0.4990, 0.2252]])

In [64]:
torch.clamp(A, min=0.4)


tensor([[0.7743, 0.8858, 0.5574],
        [0.9427, 0.4000, 0.4000],
        [0.4000, 0.4990, 0.4000]])