In [1]:
import numpy as np
import torch
import os

# Indexing and Slicing

In [2]:
a = torch.rand(size=(3,3))
a

tensor([[0.4617, 0.5344, 0.4058],
        [0.1839, 0.5077, 0.4204],
        [0.2714, 0.1504, 0.3194]])

tensor[row, col]

In [5]:
a[0,:]

tensor([0.4617, 0.5344, 0.4058])

In [6]:
a[:,0]

tensor([0.4617, 0.1839, 0.2714])

In [8]:
a[0:2,1:3]

tensor([[0.5344, 0.4058],
        [0.5077, 0.4204]])

In [9]:
a[0,0]

tensor(0.4617)

In [10]:
a[0,0] = 2

In [11]:
a

tensor([[2.0000, 0.5344, 0.4058],
        [0.1839, 0.5077, 0.4204],
        [0.2714, 0.1504, 0.3194]])

# Concatination

In [12]:
a = torch.rand(size=(3,3))
b = torch.rand(size=(3,3))

In [13]:
a, b

(tensor([[0.6233, 0.2433, 0.3443],
         [0.7285, 0.0152, 0.0433],
         [0.9805, 0.5637, 0.1887]]), tensor([[0.1579, 0.9837, 0.9291],
         [0.9645, 0.0783, 0.3794],
         [0.0164, 0.9815, 0.8248]]))

In [15]:
torch.cat((a,b)) # colwise

tensor([[0.6233, 0.2433, 0.3443],
        [0.7285, 0.0152, 0.0433],
        [0.9805, 0.5637, 0.1887],
        [0.1579, 0.9837, 0.9291],
        [0.9645, 0.0783, 0.3794],
        [0.0164, 0.9815, 0.8248]])

In [16]:
torch.cat((a, b), dim=1) # rowwise

tensor([[0.6233, 0.2433, 0.3443, 0.1579, 0.9837, 0.9291],
        [0.7285, 0.0152, 0.0433, 0.9645, 0.0783, 0.3794],
        [0.9805, 0.5637, 0.1887, 0.0164, 0.9815, 0.8248]])

# Reshaping

In [17]:
a = torch.rand(size=(3,4))

In [18]:
a.shape

torch.Size([3, 4])

In [19]:
a.reshape(2, 6)

tensor([[0.6517, 0.7043, 0.0718, 0.1254, 0.2111, 0.9440],
        [0.7074, 0.1293, 0.0654, 0.7826, 0.6903, 0.5887]])

In [20]:
a.shape

torch.Size([3, 4])

In [22]:
a.reshape(1, 12)

tensor([[0.6517, 0.7043, 0.0718, 0.1254, 0.2111, 0.9440, 0.7074, 0.1293, 0.0654,
         0.7826, 0.6903, 0.5887]])

In [24]:
a.view(-1) #Flattening

tensor([0.6517, 0.7043, 0.0718, 0.1254, 0.2111, 0.9440, 0.7074, 0.1293, 0.0654,
        0.7826, 0.6903, 0.5887])

In [25]:
a.view(-1).shape

torch.Size([12])

In [30]:
# Batch flatenning operation

batch = 16

torch.rand((batch, 2, 5))

tensor([[[0.5160, 0.6634, 0.2929, 0.7533, 0.9912],
         [0.6345, 0.8759, 0.3064, 0.9819, 0.8565]],

        [[0.6200, 0.7884, 0.8612, 0.6540, 0.2810],
         [0.3810, 0.5448, 0.1466, 0.8588, 0.0212]],

        [[0.7277, 0.1495, 0.1851, 0.8356, 0.0672],
         [0.3707, 0.2229, 0.8016, 0.7255, 0.9706]],

        [[0.5709, 0.0539, 0.2000, 0.6405, 0.3519],
         [0.6120, 0.9675, 0.3270, 0.8826, 0.8931]],

        [[0.5590, 0.3691, 0.5435, 0.3750, 0.9689],
         [0.0924, 0.2075, 0.2941, 0.3423, 0.2172]],

        [[0.0296, 0.0329, 0.5801, 0.1154, 0.1903],
         [0.5494, 0.9316, 0.3128, 0.6496, 0.9196]],

        [[0.0821, 0.7877, 0.9636, 0.7741, 0.3522],
         [0.1741, 0.6262, 0.4777, 0.4090, 0.0792]],

        [[0.3950, 0.7446, 0.4462, 0.8705, 0.9209],
         [0.5819, 0.2120, 0.9024, 0.4539, 0.6570]],

        [[0.1867, 0.9129, 0.4213, 0.9017, 0.8695],
         [0.2202, 0.6083, 0.7083, 0.8721, 0.1730]],

        [[0.2059, 0.9830, 0.3628, 0.7105, 0.6641],
         [0.1

In [31]:
torch.rand((batch, 2, 5)).view((batch, -1))

tensor([[0.5292, 0.3516, 0.1940, 0.4492, 0.7306, 0.9436, 0.5036, 0.0374, 0.4373,
         0.3171],
        [0.4197, 0.6333, 0.7914, 0.2901, 0.4351, 0.8518, 0.3914, 0.0435, 0.2450,
         0.6158],
        [0.7481, 0.4176, 0.5382, 0.7717, 0.3964, 0.7394, 0.2135, 0.9148, 0.4365,
         0.5117],
        [0.7376, 0.6022, 0.1478, 0.0870, 0.3445, 0.6848, 0.9209, 0.6256, 0.2708,
         0.2279],
        [0.2403, 0.4669, 0.5813, 0.4837, 0.9280, 0.0542, 0.9238, 0.2182, 0.7751,
         0.7784],
        [0.2123, 0.9350, 0.2114, 0.9928, 0.7742, 0.1319, 0.2348, 0.7672, 0.7231,
         0.5035],
        [0.3063, 0.8701, 0.7303, 0.5538, 0.7901, 0.3448, 0.4128, 0.6710, 0.7778,
         0.0476],
        [0.8291, 0.7281, 0.9948, 0.3821, 0.1063, 0.8513, 0.5783, 0.2948, 0.1847,
         0.2832],
        [0.9359, 0.4287, 0.8947, 0.9332, 0.4656, 0.6311, 0.3866, 0.2722, 0.3546,
         0.4399],
        [0.4251, 0.8875, 0.3108, 0.9956, 0.6865, 0.2163, 0.0029, 0.8955, 0.6586,
         0.4567],
        [0