In [5]:
import torch
import numpy as np
import os

In [3]:
torch.__version__

'1.11.0+cu113'

In [6]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

# Tensors

In [7]:
basic_tensors = torch.tensor([[1, 2, 3], [4, 5, 6]])
basic_tensors

tensor([[1, 2, 3],
        [4, 5, 6]])

In [8]:
basic_tensors.dtype

torch.int64

In [9]:
basic_tensors.device

device(type='cpu')

In [11]:
basic_tensors.requires_grad

False

In [12]:
tensor = torch.tensor([[1, 2, 3, ], [5, 6, 7]],
                      dtype=torch.float,
                      device=device,
                      requires_grad=True)
tensor

tensor([[1., 2., 3.],
        [5., 6., 7.]], requires_grad=True)

In [13]:
tensor.dtype

torch.float32

In [14]:
tensor.device

device(type='cpu')

In [15]:
tensor.requires_grad

True

# Different types of Tensors

In [18]:
empty = torch.empty(size=(3,3))
empty

tensor([[3.7508e-35, 0.0000e+00, 1.5975e-43],
        [1.3873e-43, 1.4574e-43, 6.4460e-44],
        [1.4153e-43, 1.5274e-43, 1.5695e-43]])

In [19]:
zero = torch.zeros(size=(3,3))
zero

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [20]:
one = torch.ones(size=(3,3))
one

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [21]:
random = torch.rand(size=(3,3))
random

tensor([[0.8120, 0.1444, 0.3053],
        [0.5795, 0.1850, 0.6804],
        [0.9603, 0.5535, 0.6779]])

In [22]:
identity = torch.eye(4)
identity

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [23]:
arange = torch.arange(start=0, end=12, step=1.8)
arange

tensor([ 0.0000,  1.8000,  3.6000,  5.4000,  7.2000,  9.0000, 10.8000])

In [26]:
linspace = torch.linspace(start=0, end=12, steps=10)
linspace

tensor([ 0.0000,  1.3333,  2.6667,  4.0000,  5.3333,  6.6667,  8.0000,  9.3333,
        10.6667, 12.0000])

In [30]:
normal_dist = torch.rand(size=(4,4)).normal_(mean=0, std=1)
normal_dist

tensor([[ 0.6807,  0.2871,  0.2546, -0.7922],
        [-0.6781,  0.9868,  1.4644,  1.3534],
        [-0.1899,  1.4735,  0.1177, -0.7139],
        [ 0.7490,  0.1032, -1.3622,  0.2641]])

In [32]:
uniform_dist = torch.rand(3,3).uniform_(3,5)
uniform_dist

tensor([[4.1397, 4.1025, 4.5298],
        [3.0580, 3.9162, 3.3727],
        [4.9449, 3.7660, 3.5261]])

In [33]:
diagonal = torch.diag(torch.ones(10))
diagonal

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])